import type { Metadata } from 'next';
import { ReactQueryProvider } from '@/src/core/providers/react-query/ReactQueryProvider';
import { Audiowide, Bruno_Ace } from 'next/font/google';
import '../globals.css';

const headingFont = Audiowide({
  weight: '400',
  variable: '--font-heading',
  subsets: ['latin'],
});

const bodyFont = Bruno_Ace({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${headingFont.variable} ${bodyFont.variable} h-full antialiased `}
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
