// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// Prisma does not support a TypeScript config file in this way.
// Configuration should be done in schema.prisma and .env files.
